name: 'shelf_example'
version: 0.0.1
description: A web server built using the shelf package.
author: Joel Trottier-Hebert <iamquebecois@gmail.com>
homepage: http://stacktrace.ca

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  shelf: "^0.6.4+2"
